# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_frab_identity <- function(names, values) {
    .Call(`_frab_c_frab_identity`, names, values)
}

c_frab_add <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_add`, names1, values1, names2, values2)
}

c_frab_multiply <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_multiply`, names1, values1, names2, values2)
}

c_frab_pmax <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_pmax`, names1, values1, names2, values2)
}

c_frab_eq <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_eq`, names1, values1, names2, values2)
}

sparsetable_maker <- function(M, d) {
    .Call(`_frab_sparsetable_maker`, M, d)
}

sparsetable_add <- function(M1, d1, M2, d2) {
    .Call(`_frab_sparsetable_add`, M1, d1, M2, d2)
}

sparsetable_overwrite <- function(M1, d1, M2, d2) {
    .Call(`_frab_sparsetable_overwrite`, M1, d1, M2, d2)
}

sparsetable_accessor <- function(M, d, Mindex) {
    .Call(`_frab_sparsetable_accessor`, M, d, Mindex)
}

sparsetable_setter <- function(M1, d1, M2, d2) {
    .Call(`_frab_sparsetable_setter`, M1, d1, M2, d2)
}

sparsetable_equality <- function(M1, d1, M2, d2) {
    .Call(`_frab_sparsetable_equality`, M1, d1, M2, d2)
}

sparsetable_asum_include <- function(M, d, n) {
    .Call(`_frab_sparsetable_asum_include`, M, d, n)
}

sparsetable_pmax <- function(M1, d1, M2, d2) {
    .Call(`_frab_sparsetable_pmax`, M1, d1, M2, d2)
}

