# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_frab_identity <- function(names, values) {
    .Call(`_frab_c_frab_identity`, names, values)
}

c_frab_add <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_add`, names1, values1, names2, values2)
}

c_frab_pmax <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_pmax`, names1, values1, names2, values2)
}

c_frab_eq <- function(names1, values1, names2, values2) {
    .Call(`_frab_c_frab_eq`, names1, values1, names2, values2)
}

