# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_frab_identity <- function(symbols, powers) {
    .Call(`_frab_c_frab_identity`, symbols, powers)
}

c_frab_add <- function(symbols1, powers1, symbols2, powers2) {
    .Call(`_frab_c_frab_add`, symbols1, powers1, symbols2, powers2)
}

c_frab_eq <- function(symbols1, powers1, symbols2, powers2) {
    .Call(`_frab_c_frab_eq`, symbols1, powers1, symbols2, powers2)
}

